name: breakout
description: Breakout sample game
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flame: 1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  fonts:
    - family: press-start-2p
      fonts:
        - asset: assets/press-start-2p.ttf
